### ISSUE TITLE
Default variables are not used

### ISSUE THREAD

**Issue by Chilinot** [sdarwin/Ansible-VNC#5]
The task `set facts based on defaults` does not work for me. The issue seems to be because it relies on the `vars` function, which does not return what it is expecting to return. It returns a massive dictionary.

The `item` variable inside the task is then equal to this massive dictionary, and not a single variable, as the task seem to assume.

I am running Ansible 2.9.10 using Python 3.8.3, and trying to deploy to a Centos 8 server.

**Comment by Chilinot** [comment]
I have found a fix to the issue. You have to ensure the `vars` dict is in fact handled like a list by converting the line `with_items: "{{ vars }}"` to `with_items: "{{ vars | list }}"`.

**Comment by sdarwin** [comment]
Hi @Chilinot ,
Thanks for the information. That's very interesting.  
The vars variable is expected to be a massive dictionary, but the item isn't.
I just tested with the same parameters: Ansible 2.9.10, Python 3.8.3, Centos 8 server and it succeeded.

We can consider your pull-request to fix the problem but I'd really like to understand it more first.

What, if anything, have you customized?  

Could you run ansible-playbook (both with and without verbose mode enabled) and email me the output?  Something similar to this although it could be different based on your environment.

```
ansible-playbook -i roles/sdarwin.VNC/scripts/localinventory roles/sdarwin.VNC/default.yml > outputfile1.txt
ansible-playbook -vvv -i roles/sdarwin.VNC/scripts/localinventory roles/sdarwin.VNC/default.yml > outputfile-verbose.txt
```

**Comment by Chilinot** [comment]
I have not modified the role in any way besides my above patch. This is how i use it:
**playbook**:
```
---
- name: Setup VNC
  hosts: foobar
  become: true
  vars:
    ansible_ssh_user: 'ec2-user'
  roles:
    - role: sdarwin.VNC
      tags: [ vnc ]
      vars:
        vnc_server: tigervnc
        vnc_desktop: gnome
        vnc_client_options: "-geometry 1280x720 -localhost"
        vnc_install_systemd_services: true
        vnc_bashrc_startup: true
        vnc_ansible_managed_startup_scripts: false
        vnc_ansible_managed_xstartup: false
        vnc_reboot_once: false
        vnc_users:
          - username: 'foobar'
            #port: 5900
            vnc_num: 0
            vnc_default_password: "supersecret"
```

**inventory**:
```
plugin: aws_ec2
regions:
  - us-east-1
filters:
  tag:AnsibleGroup: "foobar"
groups:
  foobar: true
compose:
  ansible_host: private_ip_address
```

Other than that, i have not added anything, or modified anything.
